version: '3.8'

services:
  nginx:
    build: ./nginx
    image: harbor01.cssnr.com/shane/blue-team-docker-nginx:${VERSION}
    env_file: ${ENV_FILE}
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    depends_on:
      - app
    secrets:
      - source: cssnr.com.crt
        target: /etc/ssl/cssnr.com.crt
      - source: cssnr.com.key
        target: /etc/ssl/cssnr.com.key
      - source: blueteam_basic_http_auth
        target: /etc/nginx/auth.users
    ports:
      - "${DOCKER_PORT}:443"

  app:
    build: ./app
    image: harbor01.cssnr.com/shane/blue-team-docker-app:${VERSION}
    env_file: ${ENV_FILE}
    command: "gunicorn blueteam.wsgi:application -w 2 -b 0.0.0.0:9000"
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    depends_on:
      - redis

  worker:
    build: ./app
    image: harbor01.cssnr.com/shane/blue-team-docker-worker:${VERSION}
    env_file: ${ENV_FILE}
    command: "celery -A blueteam worker -l INFO -c 2"
    deploy:
      mode: global
    depends_on:
      - app
      - redis

  beat:
    build: ./app
    image: harbor01.cssnr.com/shane/blue-team-docker-beat:${VERSION}
    env_file: ${ENV_FILE}
    command: "celery -A blueteam beat -l INFO -s /celerybeat-schedule"
    deploy:
      mode: global
    depends_on:
      - app
      - redis

  flower:
    image: mher/flower
    env_file: ${ENV_FILE}
    deploy:
      mode: global

  redis:
    image: redis:5-alpine
    deploy:
      mode: global

secrets:
  cssnr.com.crt:
    external: true
  cssnr.com.key:
    external: true
  blueteam_basic_http_auth:
    external: true

volumes:
  data_dir:
